<%@ Page Title="" Language="C#" MasterPageFile="~/Members/FlexiLearnMember.Master" AutoEventWireup="true" CodeBehind="UserDashboard.aspx.cs" Inherits="FlexiLearn_MarielMartinez.Members.UserDashboard" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>User Dashboard</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h1>User Dashboard</h1>
    <p>This page will show the details of any registration requests you have submitted.</p>
    <asp:GridView ID="GVRegistrationRequests" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GVRegistrationRequests_RowDeleting"></asp:GridView>
</asp:Content>
